#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Kaggle Writeup（中 / 英）→ docs/kaggle_writeup_zh.html、docs/kaggle_writeup_en.html；数字与图和技术报告共用同一数据块。
PDF：用 Chrome 打印 A4（页边 14 mm）得到 docs/kaggle_writeup_zh.pdf / _en.pdf。用法：python scripts/build_writeup.py [zh|en|all]"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
_zh = open(os.path.join(HERE, "build_tech_report.py"), encoding="utf-8").read()
exec(_zh.split('HTML = f"""', 1)[0])
e5v1 = J(f"{R}/e5_agent_tasks_claude.json")["summary"]
LANGS = sys.argv[1:] or ["all"]; LANGS = ["zh", "en"] if LANGS == ["all"] else LANGS
STYLE = f"""{CSS}
body{{background:var(--paper)}}main{{max-width:82ch}}
.decl{{border:2px solid var(--accent);border-radius:6px;padding:10px 16px;margin:14px 0;background:var(--accent-soft);font-weight:600}}
.links{{display:grid;grid-template-columns:auto 1fr;gap:4px 14px;font-size:14px;margin:12px 0}}.links b{{color:var(--muted);font-weight:500}}.links code{{font-size:13px}}
figure{{margin:16px 0}}figure img{{width:100%;border:1px solid var(--rule);border-radius:4px}}figcaption{{font-size:12.5px;color:var(--muted);line-height:1.5;margin-top:5px}}figcaption b{{color:var(--ink)}}
.two{{display:grid;grid-template-columns:1fr 1fr;gap:12px}}@media(max-width:640px){{.two{{grid-template-columns:1fr}}}}
.small{{font-size:12.5px;color:var(--muted)}}
blockquote{{border-left:3px solid var(--rule);margin:8px 0 14px;padding:6px 14px;color:var(--muted);font-size:13.5px}}
@media print{{nav.toc{{display:none}}.wrap{{display:block}}main{{max-width:none}}body{{font-size:12.5px;line-height:1.6}}h2{{break-after:avoid}}figure,table{{break-inside:avoid}}figure img{{max-height:95mm;width:auto;max-width:100%;display:block;margin:0 auto}}.two img{{max-height:70mm}}@page{{margin:14mm}}}}
"""
def e5rows(lang):
    T = {"t01": ("单图计数与大小", "single image: count and size"), "t02": ("批量分析并出报告", "batch analysis with report"), "t08": ("追问：指标含义", "follow-up: metric definitions"), "t03": ("带物理尺寸的分析", "analysis with pixel size"), "t10": ("追问：可复现性", "follow-up: reproducibility"),
         "t04": ("只数数（检测）", "count only (detection)"), "t05": ("组间比较", "group comparison"), "t06": ("生长曲线", "growth curve"), "t07": ("质控", "quality control"), "t09": ("器官未知", "organ not specified"), "t11": ("空目录", "empty folder"), "t12": ("混合器官批次", "mixed-organ batch")}
    i = 0 if lang == "zh" else 1
    return "".join(f"<tr><td>{r['id']}</td><td>{T[r['id']][i]}</td><td class='n'>{r['seconds']:.0f}</td><td class='n'>{r['tool_calls']}</td><td class='n'>{r['orgalyst_calls']}</td><td>{('通过' if lang=='zh' else 'pass') if r['ok'] else ('失败' if lang=='zh' else 'fail')}</td></tr>" for r in e5["results"])

ZH = f"""<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orgalyst · Kaggle Writeup</title><style>{STYLE}</style></head><body><div class="wrap"><main>
<header class="hd"><div class="eyebrow">AI4S Open Innovation: AI for Life Science · 第五届琶洲算法大赛 · AI + 器官芯片 · Kaggle Writeup · 2026-09-17</div>
<h1>Orgalyst：类器官明场图像的对话式智能分析系统</h1>
<p class="sub">实验人员说一句话，几分钟后拿到一份能放进实验记录、三个月后仍能复核的分析报告；报告里的每个数字都能在没有大模型的环境下用命令行重新算出来。</p></header>
<div class="decl">参赛类别：端到端系统（End-to-End System）</div>
<div class="links"><b>演示视频</b><span>3 分 43 秒，公开、免登录：https://huggingface.co/XiaoyanLi/orgalyst-weights/resolve/main/demo/orgalyst_demo.mp4（同时作为 Kaggle 附件上传）；英文配音版 https://huggingface.co/XiaoyanLi/orgalyst-weights/resolve/main/demo/orgalyst_demo_en.mp4</span><b>代码仓库</b><span>https://github.com/xiaoyanLi629/orgalyst（公开、可复现，MIT）</span><b>技术报告</b><span>PDF：https://github.com/xiaoyanLi629/orgalyst/blob/main/docs/technical_report.pdf（中文，正文 17 页 + 附录）· https://github.com/xiaoyanLi629/orgalyst/blob/main/docs/technical_report_en.pdf（英文）；同目录有 HTML 版</span><b>在线试用（可选）</b><span>https://u598784-yymh-c3389f55.weste.seetacloud.com:8443/ 账号 <code>judge</code>，密码 <code>orgalyst-judge-2026</code>。运行在一台云 GPU 实例上，评审期外可能下线；示例数据在服务器 /root/autodl-fs/AI4S/e5/data/（肠、脑、肺、胰腺癌各一小批，可直接在对话里指定），也可上传自己的明场图。备用材料：演示视频与技术报告附录 A 的截图。</span><b>模型权重</b><span>https://huggingface.co/XiaoyanLi/orgalyst-weights</span><b>数据</b><span>OrgLine（Zenodo 16355179，CC-BY-4.0）；未使用任何私有数据，未做额外标注</span><b>团队</b><span>Orgalyst Lab：Xiaoyan Li（AI / 计算机视觉 / 大模型应用，项目负责人）；许力文、付旭正（生物学，类器官培养与形态学判读，负责需求与结果审核）；姜翠翠（AI，大模型、Agent 架构与编排）；杨如美（生物学，类器官分析）。团队构成：AI / 计算机两人，生物学三人，符合赛事对跨学科团队的要求</span></div>

<h2>1 要解决的问题</h2>
<p>类器官是用干细胞在三维环境里培养出的微型组织，器官芯片把这类组织放进微流控器件里模拟生理条件。无论哪一种，最便宜、最不伤细胞、频率最高的观察手段都是明场显微镜：每天或每隔几小时拍一张，看它们长得怎么样。这些照片的分析需求非常固定：数清楚一张图里有多少个类器官，量出每个的大小和形状，比较不同处理组之间有没有差异，把同一个类器官在不同时间点的测量连成生长曲线，最后写成能放进实验记录、能被别人复核的报告。</p>
<p>瓶颈不在算法。Cellpose、OrganoID、OrgaSegment 已经能把类器官分割得相当好，OrgLine 数据集还把八个公开来源整理成了统一格式。真正卡住实验人员的是三件事：工具是给会写代码的人用的，要装环境、选模型、调直径参数，一张图上类器官大小相差十倍时默认参数会失效；分割只是第一步，后面的测量、统计、画图、写报告每个实验室都在重复造轮子，做法不一致，结果没法横向比较；没有留档，三个月后审稿人问“这个面积是用哪个版本的模型、什么参数算出来的”，多数人答不上来。</p>
<p>Orgalyst 的目标用户是做类器官或器官芯片实验、不写代码的生物学研究者。我们给自己定的成功标准有三条：用自然语言就能拿到完整的分析报告；报告里的每个数字都能用命令行在没有大模型的环境下重新算出来，并且和公开数据集自带的专家标注一致；系统对自己不确定的地方要说出来，而不是给一个看起来很准的错误数字。</p>

<h2>2 系统是什么</h2>
<p>系统分两层。<b>工具包层</b> <code>orgalyst</code> 是一个普通的 Python 包，命令行入口 <code>python -m orgalyst analyze | count | track | report</code>，不需要任何大模型；每次运行都在一个目录里留下 <code>manifest.json</code>（输入文件的 md5、模型标识与权重哈希、全部参数、软件版本、GPU 型号、逐步日志）、逐实例特征表、汇总、质控与比较表、掩码、叠加图和一份单文件 <code>report.html</code>。<b>助手层</b>基于 Claude Agent SDK，工具包通过一个 MCP 服务器暴露六个工具（列模型、分析、计数、组间比较、生长曲线、回看运行），助手负责理解需求、选器官权重、传参数、核对结果、解释；它不看图、不算数。</p>
<figure><img src="{shrink(f'{A}/overview_board.png', 1400, 80)}"><figcaption><b>图 1 · 一张肠类器官照片的完整旅程。</b>白卡片是数据，绿盒子是模型或工具，大卡片是关键环节：从一句话到助手选工具，量大小、缩放、切块、装着肠专用权重的 U-Net、三张输出图、聚成轮廓、146 个类器官轮廓、测量表、质检、统计、报告生成器，最后是报告加运行记录。交互版见仓库 docs/orgalyst_scene.html。</figcaption></figure>
<h3>2.1 工具包做了什么</h3>
<p><b>分割。</b>用 Cellpose（U-Net 回归流场，像素沿流场汇聚成实例），但不用它的通用权重直接推理，而是把 cyto3 在 OrgLine 上按脑、肠、胰腺癌、结肠分别继续训练 200 轮，得到四套专用权重；并为每种器官选定直径策略：结肠用权重里记住的训练直径，肠和胰腺癌用尺寸估计器逐图估计，脑用两遍推理（第二遍用第一遍找到目标的中位直径）。Cellpose 在类器官上最常见的失败是尺度估错，通用模型对 400 像素宽的脑类器官会估成 30 像素，零样本 AP50 只有 0.005；专用权重把尺度记住了，两遍推理又解决了脑类器官从第 2 天到第 30 天面积变化近五倍的问题。不认识的器官退回通用模型，并在报告里标注“精度较低”。</p>
<p><b>计数。</b>用户只问“有几个”时分割是浪费的，一个三器官联合训练的 YOLO11m 检测模型在不到一秒内给出数量；计数用的置信度阈值不是默认的 0.25，而是在各器官验证集上按计数误差最小标定（肠 0.50、脑 0.45、肺 0.40）。</p>
<p><b>测量、质控、统计、生长曲线。</b>测量给出面积、等效直径、周长、圆度、实心度、长宽比和是否贴边，给了像素尺寸就同时输出微米列，贴边的不完整实例默认排除并说明数量。质控分两级：图像级算清晰度、光照不均和饱和比例；实例级做翻转旋转的测试时增强，一个实例在变换后被找回的比例低于一半就标为“低可信”，报告里用橙色标出。组间比较用 Mann-Whitney 或 Kruskal-Wallis，报告 Cliff's delta 效应量，多指标 Holm 校正；生长曲线按个体、时间点、组把逐图中位面积连起来，给出相对第一个时间点的倍数。</p>
<h3>2.2 助手怎么工作</h3>
<p>光有工具还不够，助手在什么情况下该问什么、先跑什么、怎么核对、怎么汇报，我们写成了一个 skill（<code>agent/skillpack/skills/organoid-analysis</code>），用户提到类器官图片分析时自动生效。它规定四步：先确认三个前提（器官类型、像素尺寸、要数量还是形态还是比较，缺哪个问哪个，但不为简单任务阻塞）；按前提选工具（只数数走检测，其余走分割，图片少或用户关心可靠性时开质控，有分组或时间点信息时接统计）；拿到返回先核对（逐图计数出现 0 或离群值就去看叠加图，贴边排除数和低可信数必须写进回答）；最后按固定的六段格式汇报。skill 同时列出禁止事项：没有像素尺寸时不给任何微米数字，不用 Python 重算工具已经给出的统计量，不重复跑同一批图。</p>
<div class="tw"><table><tr><th>用户会怎么问</th><th>助手做什么</th><th>用户得到什么</th></tr>
<tr><td>“这批图里有几个类器官？”</td><td>检测模型逐图计数，阈值取标定值</td><td>逐图数量表、画了框的图</td></tr>
<tr><td>“分析这批肠类器官照片，告诉我大小和形状”</td><td>专用权重分割 + 测量 + 报告</td><td>总数、逐图表、面积 / 直径 / 圆度的中位数与四分位范围、report.html</td></tr>
<tr><td>“像素尺寸是 3.16 µm，面积换成平方微米”</td><td>把标定传给工具</td><td>微米单位的结果；没给标定时明确说“只报像素”</td></tr>
<tr><td>“哪些分割结果靠不住？”</td><td>开启两级质控</td><td>图像质量指标、橙色标出的低可信实例</td></tr>
<tr><td>“对照组和处理组的面积有没有差异？”</td><td>按分组文件做检验与效应量</td><td>各组中位数、p 值、Cliff's delta、箱线图，结论说人话</td></tr>
<tr><td>“从第 2 天到第 30 天长了多少？”</td><td>按个体与时间点连生长曲线</td><td>首末时间点数值与倍数、按组均值曲线</td></tr>
<tr><td>“这次用了什么模型、参数？以后怎么复现？”</td><td>读运行清单</td><td>manifest.json 路径及其记录的哈希、参数、版本</td></tr>
<tr><td>“分析 /data/x 里的图”（空目录 / 器官没说）</td><td>说明没找到图片；或用通用模型并声明精度较低</td><td>一句明确的说明，而不是一个看起来正常的数字</td></tr></table></div>
<figure><img src="{img(f'{A}/web_ui.jpg')}"><figcaption><b>图 2 · 网页版上的一次真实分析（4 张肠类器官照片）。</b>中间是助手的回答：前提说明、逐图计数表、整体形态、产物路径与建议；右上角是本对话的确认方式，右侧是助手维护的任务清单和本次对话的产物文件；底部是上下文占用与费用。同一后端还有终端版，供脚本化评测。</figcaption></figure>
<p>助手对上面这个任务的回答结尾是这样的（原文节选）。它主动说明了单位、指出没有编造像素尺寸、提示先看叠加图，并明确“201 这个数是模型输出、没有精度保证”：</p>
<blockquote>“注意：所有尺寸都是像素单位，不是微米。你没有提供 pixel_size_um，我也没有编造标定值。……建议你先翻一下 overlays/ 里的 4 张叠加图。这次用的是肠专用模型，但在没有人工标注做金标准的前提下，201 这个数仍然只是模型输出、没有精度保证。”</blockquote>

<h2>3 结果</h2>
<p>五组实验全部在 OrgLine 的测试集上完成，指标为实例级 AP50（预测与真值 IoU ≥ 0.5 记为匹配）等。</p>
<div class="tw"><table><tr><th>E1 分割 AP50</th><th class="n">cyto3 零样本</th><th class="n">按器官微调</th><th class="n">微调 + 逐图直径策略（系统默认）</th><th class="n">真值直径（上限）</th></tr>
<tr><td>brain (240)</td><td class="n">0.005</td><td class="n">0.925</td><td class="n"><b>0.967</b></td><td class="n">0.975</td></tr><tr><td>intestine (12)</td><td class="n">0.544</td><td class="n">0.773</td><td class="n"><b>0.812</b></td><td class="n">0.812</td></tr><tr><td>colon (10)</td><td class="n">0.405</td><td class="n"><b>0.815</b></td><td class="n">0.814</td><td class="n">0.800</td></tr><tr><td>pdac (20)</td><td class="n">0.419</td><td class="n">0.564</td><td class="n"><b>0.591</b></td><td class="n">0.605</td></tr></table></div>
<p>三点结论：零样本 cyto3 认得类器官但过度分割严重，微调解决了尺度与边界两个问题；直径策略的收益是真实的（脑 0.925 → 0.967，肠 0.773 → 0.812）；胰腺癌仍然弱，测试图每张 500 个以上小实例、来自另一台仪器，召回只有约一半。留一器官实验表明跨器官泛化有限（未见器官 0.15 到 0.47），专用权重是必要的；Cellpose-SAM 微调后与 cyto3 微调持平（胰腺癌 0.557、肠 0.780），权重大 50 倍、推理慢一倍，只作对照。</p>
<div class="tw"><table><tr><th>E2 检测计数（YOLO11m 联合模型）</th><th class="n">mAP50</th><th class="n">标定阈值</th><th class="n">计数 MAPE（默认 0.25 → 标定）</th><th class="n">中位相对误差</th></tr>{"".join(f"<tr><td>{o} ({cal['all'][o]['test_at_best']['n_images']})</td><td class='n'>{e2['all']['per_organ'][o]['map50']:.3f}</td><td class='n'>{cal['all'][o]['best_conf']}</td><td class='n'>{cal['all'][o]['test_at_025']['mape']:.3f} → {cal['all'][o]['test_at_best']['mape']:.3f}</td><td class='n'>{cal['all'][o]['test_at_best']['median_ape']:.2f}</td></tr>" for o in ('intestine','brain','lung'))}</table></div>
<p><b>E3 与专家标注的一致性</b>（脑，240 张，自动面积 vs 原始数据集的人工面积）：检出 {e3['n_detected']} / 漏检 {e3['n_missed']}，Spearman {e3['spearman_rho']:.3f}，中位相对误差 {e3['median_ape']*100:.1f}%，{e3['within_10pct']*100:.0f}% 的图误差 ≤ 10%。<b>E4 质控</b>（肠、结肠、胰腺癌测试集）：被标为低可信的实例中错误实例（IoU < 0.5）的占比是其余实例的 3.5 到 6.8 倍，但召回率只有 0.07 到 0.13，所以报告把它定位为“提示”而不是“过滤”。</p>
<div class="two"><figure><img src="{img(f'{A}/gallery.jpg')}"><figcaption><b>图 3 · 系统默认流程在测试集上的 12 张示例（未挑选）。</b>脑、肠、胰腺癌、结肠的分割与肺的检测计数，标题给出预测数、人工数和单图 AP50。</figcaption></figure><figure><img src="{shrink(f'{R}/e3_brain_consistency.png', 900)}"><figcaption><b>图 4 · E3 自动面积与专家面积的散点与 Bland-Altman 图。</b>残余失败集中在第 2 天最小的类器官（4 张高估）和 1 张第 30 天最大者。</figcaption></figure></div>
<p><b>E5 Agent 端到端任务集。</b>下表是加入 skill 与代码拦截后的完整复跑；加入前的第一轮同样 12/12 通过（平均 {e5v1['mean_seconds']:.0f} 秒、{e5v1['mean_tool_calls']:.1f} 次调用）。12 个自然语言任务，每个都有自动判定的成功标准：回答里的数值要落在命令行路径参考值的 5% 到 10% 之内，约定的产物文件必须存在，关键措辞必须出现。Claude（claude-opus-5）后端 {e5s['n_pass']}/{e5s['n_tasks']} 通过，平均每任务 {e5s['mean_seconds']:.0f} 秒、{e5s['mean_tool_calls']:.1f} 次工具调用（其中 {e5s['mean_orgalyst_calls']:.1f} 次为 Orgalyst 工具），合计 {e5s['total_cost_usd']:.2f} 美元。</p>
<div class="tw"><table><tr><th>任务</th><th>内容</th><th class="n">耗时 (s)</th><th class="n">工具调用</th><th class="n">其中 Orgalyst</th><th>判定</th></tr>{e5rows('zh')}</table></div>

<h2>4 可复现性</h2>
<p>仓库提供两条路径。<b>命令行路径</b>不需要任何大模型：<code>pip install -r requirements.txt</code>，<code>bash scripts/download_weights.sh</code>（权重约 200 MB，国内加 <code>--mirror</code>），然后 <code>python -m orgalyst analyze --organ intestine --images DIR --out runs</code> 即可对任意一批明场图出报告；复现报告里全部表格的脚本顺序与预期耗时（数据准备 15 分钟、E1 微调 2.5 小时、跨器官 3 小时、E2 检测 4.5 小时、E3 10 分钟、E5 25 分钟）写在 README 和技术报告第 10 节，仓库已包含我们跑出的全部结果文件，Dockerfile 覆盖这条路径。<b>Agent 路径</b>默认用 Claude API（需要评审自己的密钥），也可以通过 <code>ANTHROPIC_BASE_URL</code> 指向兼容 Anthropic 接口的开源模型网关；<code>agent/</code> 目录是助手的完整代码，不含任何账号与密钥。</p>

<h2>5 局限</h2>
<p>胰腺癌类器官的召回只有约一半，需要更多同源数据或针对小实例的多尺度推理；只有脑数据集有像素标定，其余器官只能以像素为单位；肠（12 张）和结肠（10 张）测试集很小，AP50 的置信区间宽；Agent 路径只在 Claude 一个后端上评测，12 个任务也不能覆盖真实使用里的全部问法；助手曾在工具失败时自己写分割代码“补救”，我们已在权限门卫加入硬性拦截并完整复跑了任务集；数据全部来自已发表的公开数据集，没有器官芯片的时序数据。这些都在技术报告第 8 节展开。</p>

<h2>6 影响与下一步</h2>
<p>对实验人员而言，从拍完照片到拿到报告从半天缩短到几分钟，而且报告可复核；对方法研究者而言，加一个器官只需要一份权重和一行配置。下一步最有价值的三件事：器官芯片上位置固定的类器官可以把检测框在时间上关联做逐个体追踪；在形态学指标上拟合剂量响应曲线；把助手接到成像系统的调度接口，让“拍完自动分析、异常时提醒”闭环起来。</p>
<p class="small">开发过程中使用 Claude Code 作为编程助手，代码、文档与实验脚本均经作者审核。代码 MIT；OrgLine CC-BY-4.0（不随仓库分发）；权重派生自 Cellpose（BSD-3）与 Ultralytics YOLO11（AGPL-3.0）。</p>
</main></div></body></html>"""

EN = f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orgalyst · Kaggle Writeup</title><style>{STYLE}body{{font-family:ui-sans-serif,-apple-system,"Helvetica Neue",Arial,sans-serif}}</style></head><body><div class="wrap"><main>
<header class="hd"><div class="eyebrow">AI4S Open Innovation: AI for Life Science · 5th Pazhou Algorithm Competition · AI + Organ-on-a-Chip · Kaggle Writeup · 2026-09-17</div>
<h1>Orgalyst: a conversational analysis system for organoid bright-field images</h1>
<p class="sub">A bench scientist says one sentence and, minutes later, has an analysis report that can go into the lab record and still be verified three months later; every number in it can be recomputed from the command line without any large language model.</p></header>
<div class="decl">Category: End-to-End System</div>
<div class="links"><b>Demo video</b><span>3 min 17 s (English narration), public, no login: https://huggingface.co/XiaoyanLi/orgalyst-weights/resolve/main/demo/orgalyst_demo.mp4 (also uploaded as a Kaggle attachment); English narration: https://huggingface.co/XiaoyanLi/orgalyst-weights/resolve/main/demo/orgalyst_demo_en.mp4</span><b>Code</b><span>https://github.com/xiaoyanLi629/orgalyst (public, reproducible, MIT)</span><b>Technical report</b><span>PDF: https://github.com/xiaoyanLi629/orgalyst/blob/main/docs/technical_report_en.pdf (English, 18 pages of main text plus appendix) · https://github.com/xiaoyanLi629/orgalyst/blob/main/docs/technical_report.pdf (Chinese); HTML editions in the same folder</span><b>Live demo (optional)</b><span>https://u598784-yymh-c3389f55.weste.seetacloud.com:8443/ account <code>judge</code>, password <code>orgalyst-judge-2026</code>. Runs on a single cloud GPU instance and may be offline outside the review period; sample data is on the server under /root/autodl-fs/AI4S/e5/data/ (small batches of intestine, brain, lung and pdac images, referenceable directly in the conversation), or upload your own bright-field images. Fallback: the demo video and the screenshots in Appendix A of the technical report.</span><b>Weights</b><span>https://huggingface.co/XiaoyanLi/orgalyst-weights</span><b>Data</b><span>OrgLine (Zenodo 16355179, CC-BY-4.0); no private data, no additional annotation</span><b>Team</b><span>Orgalyst Lab: Xiaoyan Li (AI / computer vision / LLM applications, project lead); Liwen Xu and Xuzheng Fu (biology: organoid culture and morphological interpretation, responsible for requirements and review of results); Cuicui Jiang (AI: large language models, agent architecture and orchestration); Rumei Yang (biology: organoid analysis). Team composition: two members from AI / computer science and three from biology, as required for the cross-disciplinary bonus</span></div>

<h2>1 The problem</h2>
<p>Organoids are miniature tissues grown from stem cells in a three-dimensional environment; organ-on-a-chip devices place such tissues into microfluidic hardware that mimics physiological conditions. In both cases the cheapest, least invasive and most frequent way to observe them is the bright-field microscope: take a picture every day or every few hours and see how they are growing. The analysis these pictures need is very fixed: count how many organoids are in an image, measure the size and shape of each, compare treatment groups, connect measurements of the same organoid over time into a growth curve, and write it up as a report that can go into the lab record and be checked by someone else.</p>
<p>The bottleneck is not the algorithm. Cellpose, OrganoID and OrgaSegment already segment organoids well, and the OrgLine dataset has unified eight public sources into one format. What actually stops bench scientists are three things. The tools are for people who write code: an environment must be installed, a model chosen and a diameter parameter tuned, and the defaults fail when organoids in one image differ tenfold in size. Segmentation is only the first step; the measuring, statistics, plotting and report writing that follow are reinvented in every lab, inconsistently. And nothing is recorded: three months later a reviewer asks which model version and which parameters produced this area, and most people cannot answer.</p>
<p>Orgalyst targets biologists who run organoid or organ-on-a-chip experiments and do not write code. We set three criteria for success: a complete analysis report from natural language alone; every number recomputable from the command line without any language model, and consistent with the expert annotation shipped with a public dataset; and a system that says when it is unsure instead of returning a wrong number that looks precise.</p>

<h2>2 What the system is</h2>
<p>Two layers. The <b>toolkit</b> <code>orgalyst</code> is an ordinary Python package with the command-line entry point <code>python -m orgalyst analyze | count | track | report</code>; it needs no language model, and every run leaves a directory with <code>manifest.json</code> (md5 of each input, model identifier and weight hash, all parameters, software versions, GPU, step log), per-instance feature tables, summaries, QC and comparison tables, masks, overlays and a single-file <code>report.html</code>. The <b>assistant</b> is built on the Claude Agent SDK; the toolkit is exposed through one MCP server as six tools (list models, analyse, count, compare groups, growth curves, review runs), and the assistant interprets the request, picks the organ weights, passes parameters, checks and explains results. It never looks at pixels or computes numbers itself.</p>
<figure><img src="{shrink(f'{A}/overview_board.png', 1400, 80)}"><figcaption><b>Figure 1 · The complete journey of one intestinal organoid image.</b> White cards are data, green boxes are models or tools, large cards are the key steps: from the user's sentence to tool selection, size estimation, rescaling, tiling, the U-Net loaded with intestine-specific weights, the three network outputs, tracking into contours, 146 organoid outlines, the measurement table, QC, statistics, the report generator, and finally the report plus the run record. Labels in Chinese; interactive version at docs/orgalyst_scene.html in the repository.</figcaption></figure>
<h3>2.1 What the toolkit does</h3>
<p><b>Segmentation.</b> Cellpose (a U-Net regressing a flow field; pixels follow the flow and converge into instances), but not with its generalist weights: we continued training cyto3 on OrgLine for 200 epochs separately for brain, intestine, pancreatic cancer (pdac) and colon, giving four organ-specific weight sets, and chose a diameter strategy per organ: colon uses the training diameter stored in the weights, intestine and pdac estimate the diameter per image with the size model, brain runs two passes (the second at the median diameter of what the first pass found). Cellpose's most common failure on organoids is scale: the generalist model estimates 30 pixels for brain organoids 400 pixels wide, giving zero-shot AP50 of 0.005. The organ weights remember the scale, and two-pass inference handles brain organoids that grow almost fivefold in area from day 2 to day 30. Unknown organs fall back to the generalist model with a "lower accuracy" notice in the report.</p>
<p><b>Counting.</b> When the user only asks how many, segmentation is wasteful; a YOLO11m detector trained jointly on three organs answers in well under a second. Its counting threshold is not the default 0.25 but the value with the lowest counting error on each organ's validation set (intestine 0.50, brain 0.45, lung 0.40).</p>
<p><b>Morphometry, QC, statistics, growth curves.</b> Measurement gives area, equivalent diameter, perimeter, circularity, solidity, aspect ratio and a border flag, with micrometre columns when a pixel size is given; incomplete border-touching instances are excluded by default and counted in the report. QC works at two levels: image-level sharpness, uneven illumination and saturation; instance-level test-time augmentation with flips and rotations, flagging an instance as "low confidence" when it is recovered in fewer than half of the transforms, drawn in orange in the report. Group comparison uses Mann-Whitney or Kruskal-Wallis with Cliff's delta and Holm correction; growth curves connect per-image median area over individuals, time points and groups and give fold change relative to the first time point.</p>
<h3>2.2 How the assistant works</h3>
<p>Tools alone are not enough. When the assistant should ask what, run what first, how to check and how to report is written as a skill (<code>agent/skillpack/skills/organoid-analysis</code>) that activates whenever the user mentions organoid image analysis. It prescribes four steps: confirm three prerequisites (organ, pixel size, and whether counts, morphology or a comparison is wanted; ask for what is missing without blocking simple tasks); choose tools from them (counting goes to detection, everything else to segmentation, QC for small batches or when reliability matters, statistics when group or time-point information exists); check the returned values before answering (an outlying per-image count triggers a look at the overlay; border exclusions and low-confidence counts must appear in the answer); report in a fixed six-part format. The skill also lists prohibitions: no micrometre figures without a pixel size, no recomputing in Python what a tool already reported, no re-running the same batch.</p>
<div class="tw"><table><tr><th>How the user asks</th><th>What the assistant does</th><th>What the user gets</th></tr>
<tr><td>"How many organoids are in these images?"</td><td>Detector counts per image at the calibrated threshold</td><td>Per-image count table, images with boxes</td></tr>
<tr><td>"Analyse these intestinal organoid images, tell me size and shape"</td><td>Organ weights, segmentation, measurement, report</td><td>Total, per-image table, medians and IQR of area / diameter / circularity, report.html</td></tr>
<tr><td>"Pixel size is 3.16 µm, give areas in µm²"</td><td>Passes the calibration to the tool</td><td>Results in micrometres; without a calibration it says "pixels only"</td></tr>
<tr><td>"Which segmentations are unreliable?"</td><td>Two-level QC</td><td>Image-quality metrics, low-confidence instances in orange</td></tr>
<tr><td>"Is there a difference in area between control and treated?"</td><td>Tests and effect sizes from a group file</td><td>Medians per group, p value, Cliff's delta, box plot, plain-language conclusion</td></tr>
<tr><td>"How much did it grow from day 2 to day 30?"</td><td>Growth curves over individuals and time points</td><td>First and last values, fold change, mean curve per group</td></tr>
<tr><td>"Which model and parameters? How do I reproduce this?"</td><td>Reads the run manifest</td><td>Path of manifest.json and the hashes, parameters and versions it records</td></tr>
<tr><td>"Analyse the images in /data/x" (empty / organ unstated)</td><td>Reports no images found; or uses the generalist model with a caveat</td><td>One clear statement instead of a plausible-looking number</td></tr></table></div>
<figure><img src="{img(f'{A}/web_ui.jpg')}"><figcaption><b>Figure 2 · A real analysis in the web interface (4 intestinal organoid images; interface language Chinese).</b> Centre: the assistant's answer with prerequisites, per-image counts, overall morphology, output paths and suggestions. Top right: the confirmation mode of this conversation; right column: the task list the assistant maintains and the files produced; bottom: context usage and spending. The same backend has a terminal edition for scripted evaluation.</figcaption></figure>
<p>The end of the assistant's answer to that task reads as follows (excerpt, translated). It states the units, says it did not invent a pixel size, suggests checking the overlays first, and states plainly that 201 is a model output without an accuracy guarantee:</p>
<blockquote>"Note: all sizes are in pixels, not micrometres. You did not provide pixel_size_um and I have not invented a calibration. … I suggest looking through the 4 overlay images in overlays/ first. This run used the intestine-specific model, but without manual annotation as a gold standard, 201 is still just a model output with no accuracy guarantee."</blockquote>

<h2>3 Results</h2>
<p>All five experiment groups were run on the OrgLine test sets; the segmentation metric is instance-level AP50 (a prediction matches a ground-truth instance at IoU ≥ 0.5).</p>
<div class="tw"><table><tr><th>E1 segmentation AP50</th><th class="n">cyto3 zero-shot</th><th class="n">Per-organ fine-tuned</th><th class="n">Fine-tuned + per-image diameter strategy (default)</th><th class="n">GT diameter (upper bound)</th></tr>
<tr><td>brain (240)</td><td class="n">0.005</td><td class="n">0.925</td><td class="n"><b>0.967</b></td><td class="n">0.975</td></tr><tr><td>intestine (12)</td><td class="n">0.544</td><td class="n">0.773</td><td class="n"><b>0.812</b></td><td class="n">0.812</td></tr><tr><td>colon (10)</td><td class="n">0.405</td><td class="n"><b>0.815</b></td><td class="n">0.814</td><td class="n">0.800</td></tr><tr><td>pdac (20)</td><td class="n">0.419</td><td class="n">0.564</td><td class="n"><b>0.591</b></td><td class="n">0.605</td></tr></table></div>
<p>Three conclusions: zero-shot cyto3 recognises organoids but over-segments badly, and fine-tuning fixes both scale and boundaries; the diameter strategies pay off (brain 0.925 → 0.967, intestine 0.773 → 0.812); pdac remains weak, with more than 500 small instances per test image from a different instrument and recall of about one half. Leave-one-organ-out experiments show limited cross-organ generalisation (0.15 to 0.47 on unseen organs), so organ-specific weights are necessary; fine-tuned Cellpose-SAM matches but does not beat fine-tuned cyto3 (pdac 0.557, intestine 0.780) with 50× larger weights and twice the inference time, so it is kept only as a comparison.</p>
<div class="tw"><table><tr><th>E2 counting (joint YOLO11m)</th><th class="n">mAP50</th><th class="n">Calibrated threshold</th><th class="n">Count MAPE (0.25 → calibrated)</th><th class="n">Median relative error</th></tr>{"".join(f"<tr><td>{o} ({cal['all'][o]['test_at_best']['n_images']})</td><td class='n'>{e2['all']['per_organ'][o]['map50']:.3f}</td><td class='n'>{cal['all'][o]['best_conf']}</td><td class='n'>{cal['all'][o]['test_at_025']['mape']:.3f} → {cal['all'][o]['test_at_best']['mape']:.3f}</td><td class='n'>{cal['all'][o]['test_at_best']['median_ape']:.2f}</td></tr>" for o in ('intestine','brain','lung'))}</table></div>
<p><b>E3 agreement with expert annotation</b> (brain, 240 images, automatic area vs the manual area in the original dataset): detected {e3['n_detected']} / missed {e3['n_missed']}, Spearman {e3['spearman_rho']:.3f}, median relative error {e3['median_ape']*100:.1f}%, {e3['within_10pct']*100:.0f}% of images within 10%. <b>E4 quality control</b> (intestine, colon and pdac test sets): the share of wrong instances (IoU < 0.5) among those flagged low-confidence is 3.5 to 6.8 times that of the rest, but recall is only 0.07 to 0.13, so the report presents the flag as a hint rather than a filter.</p>
<div class="two"><figure><img src="{img(f'{A}/gallery_en.jpg')}"><figcaption><b>Figure 3 · The default pipeline on 12 unselected test images.</b> Segmentation on brain, intestine, pdac and colon, detection counting on lung; titles give predicted count, manual count and per-image AP50.</figcaption></figure><figure><img src="{shrink(f'{R}/e3_brain_consistency.png', 900)}"><figcaption><b>Figure 4 · E3 scatter and Bland-Altman plots of automatic vs expert area.</b> Residual failures are the smallest day-2 organoids (4 over-estimated) and one of the largest day-30 ones.</figcaption></figure></div>
<p><b>E5 end-to-end agent benchmark.</b> The table is the full re-run after the skill and the code guard were added; the first run before either also passed 12/12 ({e5v1['mean_seconds']:.0f} s, {e5v1['mean_tool_calls']:.1f} calls per task).  Twelve natural-language tasks, each with an automatically judged success criterion: numbers in the answer must lie within 5 to 10% of the command-line reference values, the agreed output files must exist, and key wording must be present. With the Claude (claude-opus-5) backend {e5s['n_pass']}/{e5s['n_tasks']} tasks passed, at {e5s['mean_seconds']:.0f} s and {e5s['mean_tool_calls']:.1f} tool calls per task on average ({e5s['mean_orgalyst_calls']:.1f} of them Orgalyst tools), {e5s['total_cost_usd']:.2f} USD in total.</p>
<div class="tw"><table><tr><th>Task</th><th>Content</th><th class="n">Time (s)</th><th class="n">Tool calls</th><th class="n">of which Orgalyst</th><th>Verdict</th></tr>{e5rows('en')}</table></div>

<h2>4 Reproducibility</h2>
<p>The repository offers two paths. The <b>command-line path</b> needs no language model: <code>pip install -r requirements.txt</code>, <code>bash scripts/download_weights.sh</code> (about 200 MB), then <code>python -m orgalyst analyze --organ intestine --images DIR --out runs</code> produces a report for any folder of bright-field images. The script order and expected wall time for reproducing every table (data preparation 15 min, E1 fine-tuning 2.5 h, cross-organ 3 h, E2 detection 4.5 h, E3 10 min, E5 25 min) are in the README and section 10 of the technical report; the repository already contains all result files we produced, and a Dockerfile covers this path. The <b>agent path</b> uses the Claude API by default (reviewers need their own key) and can be pointed through <code>ANTHROPIC_BASE_URL</code> at an open-model gateway that speaks the Anthropic interface; <code>agent/</code> holds the complete assistant code with no accounts or secrets.</p>

<h2>5 Limitations</h2>
<p>Recall on pancreatic cancer organoids is only about one half and needs more in-domain data or multi-scale inference for small instances; only the brain dataset has a pixel calibration, so other organs are reported in pixels; the intestine (12) and colon (10) test sets are small and their AP50 confidence intervals wide; the agent path was evaluated on one backend and twelve tasks cannot cover every way real users phrase requests; the assistant once wrote its own segmentation code to "rescue" a failed tool call, which we have since blocked in the permission gatekeeper and re-validated with a full re-run; all data come from published datasets and none from organ-on-a-chip time series. Section 8 of the technical report expands on each.</p>

<h2>6 Impact and next steps</h2>
<p>For bench scientists, the path from image to report shrinks from half a day to minutes and the report is verifiable; for method developers, adding an organ takes one weight file and one line of configuration. The three most valuable next steps: link detection boxes over time for per-individual tracking of organoids fixed in place on a chip; fit dose-response curves to morphological metrics; and attach the assistant to the scheduling interface of an imaging system so that "analyse after imaging, alert on anomalies" closes the loop.</p>
<p class="small">Claude Code was used as a coding assistant during development; all code, documents and experiment scripts were reviewed by the authors. Code MIT; OrgLine CC-BY-4.0 (not redistributed); weights derive from Cellpose (BSD-3) and Ultralytics YOLO11 (AGPL-3.0).</p>
</main></div></body></html>"""

def _curly(html):
    parts = re.split(r"(<[^>]+>)", html); out = []
    for seg in parts:
        if seg.startswith("<"): out.append(seg); continue
        n = [0]
        def rep(m): n[0] += 1; return "“" if n[0] % 2 == 1 else "”"
        out.append(re.sub(r'"', rep, seg))
    return "".join(out)
for lang, html in (("zh", ZH), ("en", EN)):
    if lang not in LANGS: continue
    if lang == "zh": head, body = html.split("</style>", 1); html = head + "</style>" + _curly(body)
    out = f"{D}/kaggle_writeup_{lang}.html"; open(out, "w", encoding="utf-8").write(html)
    txt = re.sub(r"<[^>]+>", "", html.split("</style>", 1)[1]); print("written", out, len(html) // 1024, "KB;", (len(re.sub(r'\s', '', txt)) if lang == 'zh' else len(txt.split())), "chars/words")
